---
- hosts: all
  become: yes
  tasks:
    - name: Remove existing container if present
      shell: docker rm -f dockeransible
      ignore_errors: yes

    - name: Create new container
      shell: docker run -itd --name dockeransible -p 9000:80 vaidikprabhu/cicdpipeline


      