---
- hosts: all
  become: yes
  tasks:
  - name: create new container
    shell: 
      docker rm -f dockeransible
      docker run -itd --name dockeransible -p 9000:9000 vaidikprabhu/cicdpipeline
      